### ISSUE TITLE
Use in games

### ISSUE THREAD

**Issue by fire** [Southpaw-TACTIC/Team#4]
This repository is untouched, where is the development for the module for game teams?

**Comment by CeltonMcGrath** [comment]
Hi fire,

The TACTIC Team applications are currently outdated, and we do not plan to bring them up to date.

TACTIC is available on GitHub in the repo Southpaw-TACTIC/TACTIC.
There is a evaluation VM available from the community site,

community.southpawtech.com/community/link/downloads

TACTIC has VFX and Games templates that you can try. This might be what you are looking for.

If you have any questions about the above, please sign up to our open source community forum:

forum.southpawtech

The TACTIC Open Source team or a community member will be happy to help you.
